version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite:///witmirror.db
    volumes:
      - ./api:/app
      - witmirror_db:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  witmirror_db:
