# Fly.io configuration for WitMirror Pro
app = "witmirror-pro"
primary_region = "sjc"

[build]

[env]
  PORT = "8000"
  DATABASE_URL = "sqlite:///./witmirror.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "witmirror_data"
  destination = "/data"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
